name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_skip_job:
    runs-on: ubuntu-20.04
     # Map a step output to a job output
    outputs:
      output1: ${{ steps.checkSkip.outputs.shouldSkip }}
    steps:
      - name: "check for #skip in commit"
        id: checkSkip
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          SKIP_WORKFLOW: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}          
        run: echo "shouldSkip=$SKIP_WORKFLOW" >> "$GITHUB_OUTPUT"
  
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    needs: check_skip_job
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: npm ci
        run: npm ci
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: setup e2e:Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: check output
        env:
          OUTPUT1: ${{needs.check_skip_job.outputs.output1}}
        run: echo "ouput - $OUTPUT1"
      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.7.0
        if: ${{ github.event_name == 'push' && !env.OUTPUT1 }} 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: semver tag release
        uses: anothrNick/github-tag-action@1.70.0
        if: ${{ github.event_name == 'push' && !env.OUTPUT1 }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          WITH_V: true
          PRERELEASE: true
          DEFAULT_BUMP: 'patch'
