name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: commit messages
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          SKIP_WORKFLOW: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "COMMITS - $COMMITS \n COMMITS_2 - $COMMIT_2 \n joined - $JOIN_COMMIT_MESSAGES \n skip - $SKIP_WORKFLOW"

      - name: Print vars
        env:
          AUTHOR: ${{ toJson(github.event.commits.*.author.username) }}
          COMMIT_URL: ${{ toJson(github.event.commits.*.url) }}
        run: echo "AUTHOR - $AUTHOR \n COMMIT_URL - $COMMIT_URL"
      - name: Discord notification - job success
        uses: rjstone/discord-webhook-notify@v1.0.4
        env:
          AUTHOR: ${{ toJson(github.event.commits.*.author.username) }}
          COMMIT_URL: ${{ toJson(github.event.commits.*.url) }}
        with:
          severity: info
          username: ${{ env.AUTHOR }}
          text: New version deploy success. https://full-stack-open-pokedex-0g5z.onrender.com
          details: Commit - ${{ env.COMMIT_URL }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          AUTHOR: ${{ toJson(github.event.commits.*.author.username) }}
          COMMIT_URL: ${{ toJson(github.event.commits.*.url) }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
        