name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          SKIP_WORKFLOW: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "COMMITS - $COMMITS \n COMMITS_2 - $COMMIT_2 \n joined - $JOIN_COMMIT_MESSAGES \n skip - $SKIP_WORKFLOW"
      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
            severity: info
            details: Test succeeded.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord notification - job success
        uses: rjstone/discord-webhook-notify@v1.0.4
        env:
          AUTHOR: ${{ toJson(github.event.commits.*.author.username) }}
          COMMIT_URL: ${{ toJson(github.event.commits.*.url) }}
        with:
          severity: info
          username: ${{ env.AUTHOR }}
          text: New version deploy success. https://full-stack-open-pokedex-0g5z.onrender.com
          details: Commit - ${{ env.COMMIT_URL }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}