name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          COMMIT_MESSAGES: ${{ toJson(env.COMMITS.*.message) }}
          JOIN_COMMIT_MESSAGES: ${{ join(env.COMMIT_MESSAGES) }}
          SKIP_WORKFLOW: ${{ contains(env.COMMIT_MESSAGES, '#skip') }}
        run: echo "messages - $COMMIT_MESSAGES \n joined - $JOIN_COMMIT_MESSAGES \n skip - $SKIP_WORKFLOW"